name: Generate snake image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snk:
    runs-on: ubuntu-latest
    name: Generate snake image
    timeout-minutes: 10
    steps:
      - name: generate snake svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
