name: Generate snake image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snk:
    runs-on: ubuntu-latest
    name: Generate snake image
    timeout-minutes: 10
    steps:
      - name: generate snake svg
        uses: Platane/snk/svg-only@a69d1dbca7a94c2ef0edf10dcd9e19982d74dd39 # v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
